name: API Tests CI

on:
  push:
    branches:
      - old-version

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: newman run tests/api/auth.postman_collection.json